// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

#ifndef PROTOBUF_common_2eproto__INCLUDED
#define PROTOBUF_common_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace relax {
namespace pb {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_common_2eproto();
void protobuf_AssignDesc_common_2eproto();
void protobuf_ShutdownFile_common_2eproto();

class BASE_HEAD;

// ===================================================================

class BASE_HEAD : public ::google::protobuf::Message {
 public:
  BASE_HEAD();
  virtual ~BASE_HEAD();

  BASE_HEAD(const BASE_HEAD& from);

  inline BASE_HEAD& operator=(const BASE_HEAD& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BASE_HEAD& default_instance();

  void Swap(BASE_HEAD* other);

  // implements Message ----------------------------------------------

  BASE_HEAD* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BASE_HEAD& from);
  void MergeFrom(const BASE_HEAD& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 user_id = 1;
  inline bool has_user_id() const;
  inline void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  inline ::google::protobuf::int64 user_id() const;
  inline void set_user_id(::google::protobuf::int64 value);

  // required int32 pack_session_id = 2;
  inline bool has_pack_session_id() const;
  inline void clear_pack_session_id();
  static const int kPackSessionIdFieldNumber = 2;
  inline ::google::protobuf::int32 pack_session_id() const;
  inline void set_pack_session_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:com.relax.pb.BASE_HEAD)
 private:
  inline void set_has_user_id();
  inline void clear_has_user_id();
  inline void set_has_pack_session_id();
  inline void clear_has_pack_session_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 user_id_;
  ::google::protobuf::int32 pack_session_id_;
  friend void  protobuf_AddDesc_common_2eproto();
  friend void protobuf_AssignDesc_common_2eproto();
  friend void protobuf_ShutdownFile_common_2eproto();

  void InitAsDefaultInstance();
  static BASE_HEAD* default_instance_;
};
// ===================================================================


// ===================================================================

// BASE_HEAD

// required int64 user_id = 1;
inline bool BASE_HEAD::has_user_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BASE_HEAD::set_has_user_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BASE_HEAD::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BASE_HEAD::clear_user_id() {
  user_id_ = GOOGLE_LONGLONG(0);
  clear_has_user_id();
}
inline ::google::protobuf::int64 BASE_HEAD::user_id() const {
  // @@protoc_insertion_point(field_get:com.relax.pb.BASE_HEAD.user_id)
  return user_id_;
}
inline void BASE_HEAD::set_user_id(::google::protobuf::int64 value) {
  set_has_user_id();
  user_id_ = value;
  // @@protoc_insertion_point(field_set:com.relax.pb.BASE_HEAD.user_id)
}

// required int32 pack_session_id = 2;
inline bool BASE_HEAD::has_pack_session_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BASE_HEAD::set_has_pack_session_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BASE_HEAD::clear_has_pack_session_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BASE_HEAD::clear_pack_session_id() {
  pack_session_id_ = 0;
  clear_has_pack_session_id();
}
inline ::google::protobuf::int32 BASE_HEAD::pack_session_id() const {
  // @@protoc_insertion_point(field_get:com.relax.pb.BASE_HEAD.pack_session_id)
  return pack_session_id_;
}
inline void BASE_HEAD::set_pack_session_id(::google::protobuf::int32 value) {
  set_has_pack_session_id();
  pack_session_id_ = value;
  // @@protoc_insertion_point(field_set:com.relax.pb.BASE_HEAD.pack_session_id)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb
}  // namespace relax
}  // namespace com

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_common_2eproto__INCLUDED
